default: &default
  host: localhost
  port: 5432
  username: postgres
  adapter: postgresql
  encoding: unicode
  pool: 10

development:
  <<: *default
  database: elastic_rails_development

test:
  <<: *default
  database: elastic_rails_test